on:
  issues:
    types: [opened]
    
  pull_request_target:
    types: [opened]
    
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue edit ${{ github.event.issue.number }} --add-assignee eladb --repo ${{ github.event.repository.full_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
