on:
  issues:
    types: [opened, edited]

  pull_request_target:
    types: [opened, edited]
    
jobs:
  auto-assign:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: both
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          parameters: '[ {"keywords": [], "assignees": ["eladb"]} ]'
