name: TestOidc
on:
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@9aaa1daa91b40ce855e24cd45fb39b2ca18aeaf1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::585695036304:role/ProjenPlaygroundGitHubRole
          role-session-name: FooBar
      - run: echo "hi"
      
