name: TestOidc
on:
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::585695036304:role/ProjenPlaygroundGitHubRole
          role-session-name: MySessionName
      - run: echo "hi"
      
